#!/usr/bin/env python
# Copyright (c) 2013 Yu-Jie Lin
# Licensed under the BSD License, for detailed license information, see COPYING

from __future__ import print_function
import argparse
import sys

import smartypants
from smartypants import Attr


def main():

    parser = argparse.ArgumentParser(description=smartypants.__description__,
                                     version=smartypants.__version__)
    parser.add_argument('-a', '--attr', default='1',
                        help='processing attributes (Default: %(default)s)')
    parser.add_argument('files', metavar='FILE', type=argparse.FileType('r'),
                        nargs='*', help='files to be processed ')
    args = parser.parse_args()

    attr = 0
    for c in args.attr:
        if '0' <= c <= '3':
            c = 'set' + c
        if not hasattr(Attr, c):
            print('Unknown attribute: %s' % c, file=sys.stderr)
            sys.exit(1)
        attr |= getattr(Attr, c)

    if args.files:
        for f in args.files:
            print(smartypants.smartyPants(f.read(), attr), end='')
    else:
        print(smartypants.smartyPants(sys.stdin.read(), attr), end='')


if __name__ == '__main__':
    main()
